### ISSUE TITLE
Add cryptosuites `ecdsa-rdfc-2019` and `ecdsa-jcs-2019`

### ISSUE THREAD

**Issue by dlongley** [digitalbazaar/ecdsa-2019-cryptosuite#3]
The current implementation is for P-256 and uses RDFC, but the standard changed its name to `ecdsa-rdfc-2019`, uses a new data integrity v2 context, and additionally allows P-384. We should allow backwards compatible usage of `ecdsa-2019` but also add the new name and P-384 support. We should add JCS cryptosuite support as well or spin that off into its own library.

We could also deprecate this library and create an `ecdsa-rdfc-2019` one that supports P-256 and P-384 and another `ecdsa-jcs-2019` one -- and leave this library be. One way or another, we need to add the above capabilities.

**Comment by dlongley** [comment]
See: https://github.com/w3c/vc-di-ecdsa

**Comment by BigBlueHat** [comment]
@dlongley it looks like that "deprecation" is happening via replacement with this library: https://github.com/digitalbazaar/ecdsa-rdfc-2019-cryptosuite

Is JCS also being implemented somewhere?

Are you cool if I update this repo's readme to point to https://github.com/digitalbazaar/ecdsa-rdfc-2019-cryptosuite and possibly archive it?

**Comment by dlongley** [comment]
@BigBlueHat, yes, you can update it to point to `ecdsa-rdfc-2019-cryptosuite` but I'm not sure we have removed it from all active projects yet so we need to confirm that before archival.
